Add heading / Fix indentation
thundernest/autoconfig pull request #29
Opened 2021-12-10 08:29 UTC by mendel5

- Change formatting of README.md by adding a heading
- Fix indentation of freenet.de SMTP

2021-12-18 21:57 UTC, benbucksch requested changes

2021-12-18 21:57 UTC, benbucksch commented on README.md
> +Generic database of mail server configuration
```suggestion
# ISPDB - Generic database of mail server configuration
```

This is a generic database, not just the Thunderbird database.

2021-12-18 22:01 UTC, mendel5 commented on README.md
> +Generic database of mail server configuration
You're right!

2022-02-04 21:03 UTC, closed without merging

2022-02-05 21:30 UTC, mendel5 commented
I closed this pull request to focus on pull request https://github.com/thundernest/autoconfig/pull/31